CONTEXT_LENGTH = 64

EMBEDDING_DIM = 128
NUM_HEADS = 4
HIDDEN_DIM = 512
NUM_LAYERS = 2

BATCH_SIZE = 32

LEARNING_RATE = 3e-4

NUM_EPOCHS = 5
STEPS_PER_EPOCH = 5000

EVAL_INTERVAL = 500
EVAL_BATCHES = 100

DEVICE = "cuda" if __import__("torch").cuda.is_available() else "cpu"

EVAL_INTERVAL = 500